name: CI
on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
  # schedule:
  # - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - id: nvm
        run: echo "##NVMRC $(cat .nvmrc)" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install --no-optional --no-audit --no-fund --progress=false
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: ./manage.py makemigrations --check
      - run: ./manage.py migrate
      - run: ./manage.py loaddata fixtures.json
      - run: ./manage.py runserver &
      - run: mkdir pa11y/lighthouse
      - run: mkdir pa11y/screenshots
      - run: npm run test
      - run: node pa11y/report.js
      - run: mv pa11y/report.html pa11y/index.html
      - uses: actions/upload-artifact@v3
        with:
          name: pa11y
          path: pa11y
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          branch: gh-pages
          folder: pa11y
          clean: true
